In [87]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.2
[notice] To update, run: c:\Users\K Shiva Prasad Reddy\OneDrive\Desktop\python\Python\.venv\Scripts\python.exe -m pip install --upgrade pip


In [88]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.sum())


15


In [39]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
b = np.zeros([2,3])
print(b)
c = np.ones([1,2])
print(c)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]


In [41]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.max())
print(a.min())

5
1


In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
r1 = a*b
r2 = a*2
print(r1)
print(r2)

[5 8 9 8 5]
[ 2  4  6  8 10]


In [31]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([])
print(a)
print(b)

[1 2 3 4 5]
[]


In [18]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a.ndim)

2


In [22]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
import numpy as np
np.arange(1,10,2).reshape(5,1)


array([[1],
       [3],
       [5],
       [7],
       [9]])

In [24]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [29]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3,3],[4,5,6,4],[7,8,9,5]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 4)


In [59]:
import numpy as np
a = np.array([[1,2,3,3],[4,5,6,4],[7,8,9,5]])
print(a[::1])
print()
print(a[::-1])
print()
print(a[1,2])
print(a[2,1])
print(a[2,0])

[[1 2 3 3]
 [4 5 6 4]
 [7 8 9 5]]

[[7 8 9 5]
 [4 5 6 4]
 [1 2 3 3]]

6
8
7


In [69]:
import numpy as np
a = np.array([[1,2,3,3],[4,5,6,4],[7,8,9,5]])
condition = a > 3
print(a[condition])

[4 5 6 4 7 8 9 5]


In [9]:
import numpy as np
a = np.array([[1,2,3,3],[4,5,6,4],[7,8,9,5]])
print(np.sort(a))
print()
print(a[::-1])

[[1 2 3 3]
 [4 4 5 6]
 [5 7 8 9]]

[[7 8 9 5]
 [4 5 6 4]
 [1 2 3 3]]


In [23]:
import numpy as np
arr = np.random.randint(1,50, size=(5,5))
print(arr)
arr[2,0:]=1
print(arr)


[[45 46 42  1 37]
 [36 30 17 40 12]
 [23 23 10 32 44]
 [16 46 35 25 17]
 [25 40  2 25 31]]
[[45 46 42  1 37]
 [36 30 17 40 12]
 [ 1  1  1  1  1]
 [16 46 35 25 17]
 [25 40  2 25 31]]


In [31]:
import numpy as np
a = np.random.randint(1,16, size=(4,4))
print(a)
np.fill_diagonal(a,0)
print(a)

[[11  7 15  2]
 [ 7  1  1 11]
 [ 4  8  7  4]
 [12  5  7 12]]
[[ 0  7 15  2]
 [ 7  0  1 11]
 [ 4  8  0  4]
 [12  5  7  0]]


In [41]:
import numpy as np
arr = np.random.randint(1,36, size=(6,6))
print("old array\n" ,arr)
a = arr[2:5,1:4]
print("new array\n",a)



old array
 [[28  8 26 13 32  2]
 [ 2 34 30 22  5  4]
 [ 9 26  2  6 21  3]
 [16  4 18 23 32 35]
 [27 16  7 14 24 16]
 [31 12 21 14 34  5]]
new array
 [[26  2  6]
 [ 4 18 23]
 [16  7 14]]


In [86]:
import numpy as np
arr = np.random.randint(1,36, size=(6,6))
print("old array\n" ,arr)
border = np.concatenate([
    arr[0, :],
    arr[-1, : ],
    arr[1:-1, 0],
    arr[1:-1, -1]
       
])

print("new array\n",border)

old array
 [[21 17 21  2 24  4]
 [ 1  7 21 13 33  6]
 [23 16  7 23 34 32]
 [ 6 31 19 21 21 18]
 [12 21 27 14 32 31]
 [13 21 14 32 29 10]]
new array
 [21 17 21  2 24  4 13 21 14 32 29 10  1 23  6 12  6 32 18 31]


In [89]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
c = a+b
print(c)
d = a-b
print(d)
e = a*b
print(e)
f = a/b
print(f)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


In [94]:
a = np.random.randint(1,20, size=(1,6))
print("original : " ,a)
mean = a.mean()
print("mean : " ,mean)
std_dev = a.std()
print("standard deviation : " ,std_dev)
median = np.median(a)
print("median : " ,median)
variance = np.var(a)
print("variance : " ,variance)


original :  [[15  8  2  1 12  1]]
mean :  6.5
standard deviation :  5.560275772537426
median :  5.0
variance :  30.916666666666668


In [95]:
a = np.random.randint(1,20, size=(1,6))
print("original : " ,a)
mean = a.mean()
print("mean : " ,mean)
std_dev = a.std()
print("standard deviation : " ,std_dev)

normalized = (a-mean)/std_dev
print("normalized : " ,normalized)

original :  [[ 5 13  7  8 17 18]]
mean :  11.333333333333334
standard deviation :  4.988876515698588
normalized :  [[-1.2694909   0.33407655 -0.86859904 -0.6681531   1.13586028  1.33630621]]


In [97]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 6  4 10]
 [10  5  3]
 [ 2  3  2]]
1D array:
[9 3 4]
Resulting array:
[[15  7 14]
 [19  8  7]
 [11  6  6]]
