In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [30]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.sum())


15


In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
r1 = a*b
r2 = a*2
print(r1)
print(r2)

[5 8 9 8 5]
[ 2  4  6  8 10]


In [18]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a.ndim)

2


In [22]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [29]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3,3],[4,5,6,4],[7,8,9,5]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 4)
